Configure API Key Middleware
BigSamu/OpenSearch_Changeset_Bot pull request #4
Opened 2024-01-14 06:58 UTC by JohnathonBowers

## Description

These changes implement middleware for validating API keys sent in request headers coming from `OpenSearch_Parse_Changelog_Action` workflow runs.

## Features

In order to secure sensitive information and ensure proper error handling, this PR:

- creates a `validateChangelogPRBridgeSecretKey` middleware function, which (1) checks to make sure that an API key has been configured in the deployed instance of the Express app, (2) compares the configured API key (`authorizedApiKey`) with the key in the request header (`receivedApiKey`) to make sure that a matching key is present, and (3) either throws errors as necessary or calls the next middleware function

- configures the `validateChangelogPRBridgeSecretKey` middleware function in the Express application flow in `main.js`. The middleware applies to all routes and is invoked immediately after the request body is parsed so that no further action is taken if an API key is missing or invalid.

- creates a new `errors` directory for modularizing the construction of custom error classes. A base `CustomError` class is declared in `base.errors.js`. The error classes pertinent to API key validation extend this `CustomError` class and are declared in `auth.errors.js`. They distinguish between messages that are intended for server-side debugging (`internalMessage`) and general messages to be sent back on the response object (`publicMessage`).

- adds an entry in the `.env.sample` file to prompt contributors to configure their own keys when developing in their local environments.

## Testing

These changes have been tested manually in my local environment to make sure that the middleware and error handling work as expected.

**NOTE:** In order for this middleware to work properly, an environment variable must be configured in the deployed instance of the Express application. This variable must be named `CHANGELOG_PR_BRIDGE_SECRET_KEY`, and the value must be identical to what is set as a repository secret in the *base repository* that uses the `OpenSearch_Parse_Changelog_Action` in a workflow run.

## Issues

Resolves Issue #2

2024-01-18 19:52 UTC, BigSamu requested changes

2024-01-18 19:52 UTC, BigSamu commented on src/errors/auth.errors.js
> +    }
I would only have one error type called `UnauthorizedAPIKeyError`

2024-01-18 19:52 UTC, BigSamu commented on src/errors/base.errors.js
> +        this.publicMessage = publicMessage;
Let's use just one message variable. It is less cumbersome

2024-01-18 19:52 UTC, BigSamu commented on src/middlewares/auth.middlewares.js
> +import { AuthorizedAPIKeyNotConfiguredError, UnauthorizedAPIKeyReceivedError } from "../errors/index.js";
Just import `UnauthorizedApiKeyError `and use it in the code

2024-01-18 19:52 UTC, BigSamu commented on src/middlewares/auth.middlewares.js
> +  }
Remove this

```suggestion
```

2024-01-18 19:52 UTC, BigSamu commented on src/middlewares/error.middlewares.js
> +  console.error(err.internalMessage || err.stack);
```suggestion
  console.error(err.stack);
```

2024-01-18 19:52 UTC, BigSamu commented on src/middlewares/error.middlewares.js
> +  const message = err.publicMessage || err.message || "Internal Server Error";
```suggestion
  const message = err.message || "Internal Server Error";
```

2024-01-18 19:52 UTC, BigSamu commented on src/main.js
> +  validateChangelogPRBridgeSecretKey,
I would change the name of the function from `validateChangelogPRBridgeSecretKey` to `verifyAuthorizationApiRequest` for better consistency.

2024-01-18 19:52 UTC, BigSamu commented on src/middlewares/auth.middlewares.js
> +  const authorizedApiKey = CHANGELOG_PR_BRIDGE_SECRET_KEY;
avoid DRY

```suggestion
```

2024-01-18 19:52 UTC, BigSamu commented on src/middlewares/auth.middlewares.js
> +  }
```suggestion
  if (!receivedApiKey || receivedApiKey !== CHANGELOG_PR_BRIDGE_SECRET_KEY) {
    throw new UnauthorizedApiKeyError();
  }
```

2024-01-19 00:25 UTC, JohnathonBowers commented on src/errors/base.errors.js
> +        this.publicMessage = publicMessage;
Sounds good. I'll make this change.

2024-01-19 00:31 UTC, JohnathonBowers commented on src/errors/auth.errors.js
> +    }
Sounds good. I've removed the `AuthorizedAPIKeyNotConfiguredError` and changed the name of `UnauthorizedAPIKeyReceivedError` to `UnauthorizedAPIKeyError`.

2024-01-19 00:36 UTC, JohnathonBowers commented on src/middlewares/auth.middlewares.js
> +import { AuthorizedAPIKeyNotConfiguredError, UnauthorizedAPIKeyReceivedError } from "../errors/index.js";
Sounds good. I've made this change.

2024-01-19 00:40 UTC, JohnathonBowers commented on src/middlewares/auth.middlewares.js
> +  const authorizedApiKey = CHANGELOG_PR_BRIDGE_SECRET_KEY;
I'm not sure how the code is repeating itself here. The `receivedApiKey` is the key coming in on the request header. The `authorizedApiKey` is the key stored on the server that the `receivedApiKey` will be checked against. We need both of these variables for the authentication to take place.

2024-01-19 00:42 UTC, JohnathonBowers commented on src/middlewares/auth.middlewares.js
> +  const authorizedApiKey = CHANGELOG_PR_BRIDGE_SECRET_KEY;
The reason I stored `CHANGELOG_PR_BRIDGE_SECRET_KEY` in a different variable is to make the code more readable. These variables make it easier to understand the source of each key.

2024-01-19 01:05 UTC, JohnathonBowers commented on src/middlewares/auth.middlewares.js
> +  }
Simplifying this to:

```
if (receivedApiKey !== authorizedApiKey) {
    throw new UnauthorizedApiKeyError();
}
```

If there is no API key coming in on the request header, then, by necessity, it won't match the API key stored on the server. So, the additional check for the existince of an API key on the request header is unnecessary.

2024-01-19 01:06 UTC, JohnathonBowers commented on src/middlewares/auth.middlewares.js
> +  }
Removed.

2024-01-19 14:11 UTC, JohnathonBowers commented on src/main.js
> +  validateChangelogPRBridgeSecretKey,
To keep consistent with the way the incoming API key is named in the middleware function, I'll name this function `verifyReceivedApiKey` for now. We can change it later if we feel there is a better name.

2024-01-19 14:23 UTC, JohnathonBowers commented on src/middlewares/error.middlewares.js
> +  console.error(err.internalMessage || err.stack);
Change made.

2024-01-19 14:24 UTC, JohnathonBowers commented on src/middlewares/error.middlewares.js
> +  const message = err.publicMessage || err.message || "Internal Server Error";
Changed.

2024-01-19 14:58 UTC, BigSamu commented on src/main.js
> +  validateChangelogPRBridgeSecretKey,
Ok perfect!

2024-01-19 15:01 UTC, BigSamu commented on src/middlewares/auth.middlewares.js
> +  const authorizedApiKey = CHANGELOG_PR_BRIDGE_SECRET_KEY;
Mmmm, you are repeating yourself here. I prefer to be concise a have the fewer lines possible. Indeed the constant `CHANGELOG_PR_BRIDGE_SECRET_KEY` we change it to `CHANGELOG_PR_BRIDGE_API_KEY`, so this is enough for readability.  

Anyway your call on this. Don't want to be a stopper.

2024-01-19 15:03 UTC, BigSamu commented on src/middlewares/auth.middlewares.js
> +  }
I would say

```js
if (receivedApiKey !== CHANGELOG_PR_BRIDGE_API_KEY) {
    throw new UnauthorizedApiKeyError();
}
```

But once again, your call on this

2024-01-19 16:27 UTC, BigSamu commented on src/middlewares/auth.middlewares.js
> +  }
@JohnathonBowers,

At last I check this and you should have

```js
if (!receivedApiKey || receivedApiKey !== authorizedApiKey) {
    throw new UnauthorizedAPIKeyError();
  }
  ```
  
  What if `receivedApiKey` is `undefined` and `authorizedApiKey` is also `undefined`. In that case, the request passed through (I tested with Postman).

2024-01-19 16:37 UTC, BigSamu approved these changes

2024-01-19 19:23 UTC, JohnathonBowers commented on src/middlewares/auth.middlewares.js
> +  }
Good point. I had thought about that possibility after making this comment. I agree we should include the check for the presence of the receivedApiKey in the function.

2024-01-20 12:20 UTC, merged